<script type='text/javascript' src='https://www.google.com/jsapi'></script>
<script type='text/javascript'>
	google.load('visualization', '1', {'packages': ['geochart']});
	google.setOnLoadCallback(drawRegionsMap);
	
	function drawRegionsMap() {
		// Create our data table.
		var data = google.visualization.arrayToDataTable(<?php echo $this->datatableGeo; ?>);
		
		var options = {	width:834, 
								height:520};
		
		var container = document.getElementById('map_canvas');
		var geochart = new google.visualization.GeoChart(container);
		geochart.draw(data, options);
	};
</script>
<h1>Provenance des clients</h1>
<div id='map_canvas'></div>