<div class="main_pic"><img src="/img/Maison-logo.jpg"></div>
<div class="main_opt">
<h1>Statisques de reservations</h1>
<a class="button big" href="<?php echo $this->url(array('controller'=>'clients', 'action'=>'frommap')); ?>">Provenance des clients</a>
<a class="button big" href="<?php echo $this->url(array('controller'=>'clients', 'action'=>'tauxoccup')); ?>">Taux d'occupation</a>
<a class="button big" href="<?php echo $this->url(array('controller'=>'clients', 'action'=>'fromsites')); ?>">Sites web referents</a>
<a class="button big" href="<?php echo $this->url(array('controller'=>'clients', 'action'=>'advancedstats')); ?>">Statistiques avancées</a>
</div>